/**
 * Referências de Salmos usadas no card "Verso do dia" do Dashboard.
 *
 * O campo `text` está vazio de propósito: textos de traduções bíblicas em
 * português (ARA, ARC, NVI, ACF etc.) normalmente têm direitos autorais das
 * sociedades bíblicas, e não há como garantir aqui uma citação fiel e
 * licenciada. Antes de usar em produção, preencha `text` com o texto de uma
 * tradução que você tenha o direito de reproduzir (uma tradução de domínio
 * público verificada, ou uma tradução para a qual você tenha permissão de uso).
 *
 * Enquanto `text` estiver vazio, o card mostra apenas a referência.
 */
const PSALMS = Object.freeze([
  { reference: "Salmos 3:3", text: "" },
  { reference: "Salmos 4:8", text: "" },
  { reference: "Salmos 5:11", text: "" },
  { reference: "Salmos 6:2", text: "" },
  { reference: "Salmos 9:9", text: "" },
  { reference: "Salmos 16:8", text: "" },
  { reference: "Salmos 16:11", text: "" },
  { reference: "Salmos 18:2", text: "" },
  { reference: "Salmos 18:6", text: "" },
  { reference: "Salmos 20:1", text: "" },
  { reference: "Salmos 20:7", text: "" },
  { reference: "Salmos 23:1", text: "" },
  { reference: "Salmos 23:2", text: "" },
  { reference: "Salmos 23:3", text: "" },
  { reference: "Salmos 23:4", text: "" },
  { reference: "Salmos 23:6", text: "" },
  { reference: "Salmos 25:4-5", text: "" },
  { reference: "Salmos 27:1", text: "" },
  { reference: "Salmos 27:5", text: "" },
  { reference: "Salmos 27:13-14", text: "" },
  { reference: "Salmos 28:7", text: "" },
  { reference: "Salmos 29:11", text: "" },
  { reference: "Salmos 30:2", text: "" },
  { reference: "Salmos 30:5", text: "" },
  { reference: "Salmos 31:3", text: "" },
  { reference: "Salmos 31:7", text: "" },
  { reference: "Salmos 31:24", text: "" },
  { reference: "Salmos 32:7", text: "" },
  { reference: "Salmos 33:20", text: "" },
  { reference: "Salmos 34:4", text: "" },
  { reference: "Salmos 34:7", text: "" },
  { reference: "Salmos 34:17", text: "" },
  { reference: "Salmos 34:18", text: "" },
  { reference: "Salmos 34:19", text: "" },
  { reference: "Salmos 37:3", text: "" },
  { reference: "Salmos 37:4", text: "" },
  { reference: "Salmos 37:5", text: "" },
  { reference: "Salmos 37:23-24", text: "" },
  { reference: "Salmos 40:1", text: "" },
  { reference: "Salmos 40:2", text: "" },
  { reference: "Salmos 41:1", text: "" },
  { reference: "Salmos 41:3", text: "" },
  { reference: "Salmos 42:5", text: "" },
  { reference: "Salmos 46:1", text: "" },
  { reference: "Salmos 46:10", text: "" },
  { reference: "Salmos 54:4", text: "" },
  { reference: "Salmos 55:22", text: "" },
  { reference: "Salmos 56:3", text: "" },
  { reference: "Salmos 56:4", text: "" },
  { reference: "Salmos 57:1", text: "" },
  { reference: "Salmos 61:2", text: "" },
  { reference: "Salmos 62:1", text: "" },
  { reference: "Salmos 62:2", text: "" },
  { reference: "Salmos 62:5-6", text: "" },
  { reference: "Salmos 63:7", text: "" },
  { reference: "Salmos 68:19", text: "" },
  { reference: "Salmos 71:5", text: "" },
  { reference: "Salmos 71:20-21", text: "" },
  { reference: "Salmos 73:26", text: "" },
  { reference: "Salmos 84:11", text: "" },
  { reference: "Salmos 86:7", text: "" },
  { reference: "Salmos 86:11", text: "" },
  { reference: "Salmos 90:14", text: "" },
  { reference: "Salmos 91:1", text: "" },
  { reference: "Salmos 91:2", text: "" },
  { reference: "Salmos 91:4", text: "" },
  { reference: "Salmos 91:5", text: "" },
  { reference: "Salmos 91:10", text: "" },
  { reference: "Salmos 91:11", text: "" },
  { reference: "Salmos 91:14", text: "" },
  { reference: "Salmos 91:15", text: "" },
  { reference: "Salmos 91:16", text: "" },
  { reference: "Salmos 94:18", text: "" },
  { reference: "Salmos 94:19", text: "" },
  { reference: "Salmos 103:2", text: "" },
  { reference: "Salmos 103:3", text: "" },
  { reference: "Salmos 103:4", text: "" },
  { reference: "Salmos 107:19", text: "" },
  { reference: "Salmos 107:20", text: "" },
  { reference: "Salmos 112:7", text: "" },
  { reference: "Salmos 116:1", text: "" },
  { reference: "Salmos 116:2", text: "" },
  { reference: "Salmos 118:5", text: "" },
  { reference: "Salmos 118:6", text: "" },
  { reference: "Salmos 118:17", text: "" },
  { reference: "Salmos 119:28", text: "" },
  { reference: "Salmos 119:50", text: "" },
  { reference: "Salmos 119:76", text: "" },
  { reference: "Salmos 119:105", text: "" },
  { reference: "Salmos 119:114", text: "" },
  { reference: "Salmos 121:1", text: "" },
  { reference: "Salmos 121:2", text: "" },
  { reference: "Salmos 121:3", text: "" },
  { reference: "Salmos 121:4", text: "" },
  { reference: "Salmos 121:5", text: "" },
  { reference: "Salmos 121:7", text: "" },
  { reference: "Salmos 121:8", text: "" },
  { reference: "Salmos 125:1", text: "" },
  { reference: "Salmos 126:5", text: "" },
  { reference: "Salmos 130:5", text: "" },
  { reference: "Salmos 138:3", text: "" },
  { reference: "Salmos 138:7", text: "" },
  { reference: "Salmos 139:1-3", text: "" },
  { reference: "Salmos 139:7", text: "" },
  { reference: "Salmos 139:11-12", text: "" },
  { reference: "Salmos 143:8", text: "" },
  { reference: "Salmos 145:8", text: "" },
  { reference: "Salmos 145:9", text: "" },
  { reference: "Salmos 145:14", text: "" },
  { reference: "Salmos 145:18", text: "" },
  { reference: "Salmos 146:5", text: "" },
  { reference: "Salmos 147:3", text: "" },
  { reference: "Salmos 147:11", text: "" },
]);
