/**
 * Referências de Salmos usadas no card "Verso do dia" do Dashboard.
 *
 * Texto: tradução de João Ferreira de Almeida (edição histórica, de domínio
 * público), obtido via a API pública bible-api.com, que serve o texto do
 * projeto open-bibles (por-almeida.usfx.xml, marcado como domínio público).
 * Alguns versículos tiveram apenas a letra inicial maiúscula ajustada e a
 * pontuação final normalizada para ponto final, por terem sido extraídos
 * isoladamente de uma frase que continua no versículo seguinte no texto
 * original; as palavras não foram alteradas.
 */
const PSALMS = Object.freeze([
  { reference: "Salmos 3:3", text: "Mas tu, Senhor, és um escudo ao redor de mim, a minha glória, e aquele que exulta a minha cabeça." },
  { reference: "Salmos 4:8", text: "Em paz me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança." },
  { reference: "Salmos 5:11", text: "Mas alegrem-se todos os que confiam em ti; exultem eternamente, porquanto tu os defendes; sim, gloriem-se em ti os que amam o teu nome." },
  { reference: "Salmos 6:2", text: "Tem compaixão de mim, Senhor, porque sou fraco; sara-me, Senhor, porque os meus ossos estão perturbados." },
  { reference: "Salmos 9:9", text: "O Senhor é também um alto refúgio para o oprimido, um alto refúgio em tempos de angústia." },
  { reference: "Salmos 16:8", text: "Tenho posto o Senhor continuamente diante de mim; porquanto ele está à minha mão direita, não serei abalado." },
  { reference: "Salmos 16:11", text: "Tu me farás conhecer a vereda da vida; na tua presença há plenitude de alegria; à tua mão direita há delícias perpetuamente." },
  { reference: "Salmos 18:2", text: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus, o meu rochedo, em quem me refúgio; o meu escudo, a força da minha salvação, e o meu alto refúgio." },
  { reference: "Salmos 18:6", text: "Na minha angústia invoquei o Senhor, sim, clamei ao meu Deus; do seu templo ouviu ele a minha voz; o clamor que eu lhe fiz chegou aos seus ouvidos." },
  { reference: "Salmos 20:1", text: "O Senhor te ouça no dia da angústia; o nome do Deus de Jacó te proteja." },
  { reference: "Salmos 20:7", text: "Uns confiam em carros e outros em cavalos, mas nós faremos menção do nome do Senhor nosso Deus." },
  { reference: "Salmos 23:1", text: "O Senhor é o meu pastor; nada me faltará." },
  { reference: "Salmos 23:2", text: "Deitar-me faz em pastos verdejantes; guia-me mansamente a águas tranqüilas." },
  { reference: "Salmos 23:3", text: "Refrigera a minha alma; guia-me nas veredas da justiça por amor do seu nome." },
  { reference: "Salmos 23:4", text: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam." },
  { reference: "Salmos 23:6", text: "Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida, e habitarei na casa do Senhor por longos dias." },
  { reference: "Salmos 25:4-5", text: "Faze-me saber os teus caminhos, Senhor; ensina-me as tuas veredas. Guia-me na tua verdade, e ensina-me; pois tu és o Deus da minha salvação; por ti espero o dia todo." },
  { reference: "Salmos 27:1", text: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?" },
  { reference: "Salmos 27:5", text: "Pois no dia da adversidade me esconderá no seu pavilhão; no recôndito do seu tabernáculo me esconderá; sobre uma rocha me elevará." },
  { reference: "Salmos 27:13-14", text: "Creio que hei de ver a bondade do Senhor na terra dos viventes. Espera tu pelo Senhor; anima-te, e fortalece o teu coração; espera, pois, pelo Senhor." },
  { reference: "Salmos 28:7", text: "O Senhor é a minha força e o meu escudo; nele confiou o meu coração, e fui socorrido; pelo que o meu coração salta de prazer, e com o meu cântico o louvarei." },
  { reference: "Salmos 29:11", text: "O Senhor dará força ao seu povo; o Senhor abençoará o seu povo com paz." },
  { reference: "Salmos 30:2", text: "Ó Senhor, Deus meu, a ti clamei, e tu me curaste." },
  { reference: "Salmos 30:5", text: "Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite; pela manhã, porém, vem o cântico de júbilo." },
  { reference: "Salmos 31:3", text: "Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me." },
  { reference: "Salmos 31:7", text: "Eu me alegrarei e regozijarei na tua benignidade, pois tens visto a minha aflição. Tens conhecido as minhas angústias." },
  { reference: "Salmos 31:24", text: "Esforçai-vos, e fortaleça-se o vosso coração, vós todos os que esperais no Senhor." },
  { reference: "Salmos 32:7", text: "Tu és o meu esconderijo; preservas-me da angústia; de alegres cânticos de livramento me cercas." },
  { reference: "Salmos 33:20", text: "A nossa alma espera no Senhor; ele é o nosso auxílio e o nosso escudo." },
  { reference: "Salmos 34:4", text: "Busquei ao Senhor, e ele me respondeu, e de todos os meus temores me livrou." },
  { reference: "Salmos 34:7", text: "O anjo do Senhor acampa-se ao redor dos que o temem, e os livra." },
  { reference: "Salmos 34:17", text: "Os justos clamam, e o Senhor os ouve, e os livra de todas as suas angústias." },
  { reference: "Salmos 34:18", text: "Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito." },
  { reference: "Salmos 34:19", text: "Muitas são as aflições do justo, mas de todas elas o Senhor o livra." },
  { reference: "Salmos 37:3", text: "Confia no Senhor e faze o bem; assim habitarás na terra, e te alimentarás em segurança." },
  { reference: "Salmos 37:4", text: "Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração." },
  { reference: "Salmos 37:5", text: "Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará." },
  { reference: "Salmos 37:23-24", text: "Confirmados pelo Senhor são os passos do homem em cujo caminho ele se deleita; ainda que caia, não ficará prostrado, pois o Senhor lhe segura a mão." },
  { reference: "Salmos 40:1", text: "Esperei com paciência pelo Senhor, e ele se inclinou para mim e ouviu o meu clamor." },
  { reference: "Salmos 40:2", text: "Também me tirou duma cova de destruição, dum charco de lodo; pôs os meus pés sobre uma rocha, firmou os meus passos." },
  { reference: "Salmos 41:1", text: "Bem-aventurado é aquele que considera o pobre; o Senhor o livrará no dia do mal." },
  { reference: "Salmos 41:3", text: "O Senhor o sustentará no leito da enfermidade; tu lhe amaciarás a cama na sua doença." },
  { reference: "Salmos 42:5", text: "Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei pela salvação que há na sua presença." },
  { reference: "Salmos 46:1", text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." },
  { reference: "Salmos 46:10", text: "Aquietai-vos, e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra." },
  { reference: "Salmos 54:4", text: "Eis que Deus é o meu ajudador; o Senhor é quem sustenta a minha vida." },
  { reference: "Salmos 55:22", text: "Lança o teu fardo sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado." },
  { reference: "Salmos 56:3", text: "No dia em que eu temer, hei de confiar em ti." },
  { reference: "Salmos 56:4", text: "Em Deus, cuja palavra eu louvo, em Deus ponho a minha confiança e não terei medo." },
  { reference: "Salmos 57:1", text: "Compadece-te de mim, ó Deus, compadece-te de mim, pois em ti se refugia a minha alma; à sombra das tuas asas me refugiarei, até que passem as calamidades." },
  { reference: "Salmos 61:2", text: "Desde a extremidade da terra clamo a ti, estando abatido o meu coração; leva-me para a rocha que é mais alta do que eu." },
  { reference: "Salmos 62:1", text: "Somente em Deus espera silenciosa a minha alma; dele vem a minha salvação." },
  { reference: "Salmos 62:2", text: "Só ele é a minha rocha e a minha salvação; é ele a minha fortaleza; não serei grandemente abalado." },
  { reference: "Salmos 62:5-6", text: "Ó minha alma, espera silenciosa somente em Deus, porque dele vem a minha esperança. Só ele é a minha rocha e a minha salvação; é a minha fortaleza; não serei abalado." },
  { reference: "Salmos 63:7", text: "Pois tu tens sido o meu auxílio; de júbilo canto à sombra das tuas asas." },
  { reference: "Salmos 68:19", text: "Bendito seja o Senhor, que diariamente leva a nossa carga, o Deus que é a nossa salvação." },
  { reference: "Salmos 71:5", text: "Pois tu és a minha esperança, Senhor Deus; tu és a minha confiança desde a minha mocidade." },
  { reference: "Salmos 71:20-21", text: "Tu, que me fizeste ver muitas e penosas tribulações, de novo me restituirás a vida, e de novo me tirarás dos abismos da terra. Aumentarás a minha grandeza, e de novo me consolarás." },
  { reference: "Salmos 73:26", text: "A minha carne e o meu coração desfalecem; do meu coração, porém, Deus é a fortaleza, e o meu quinhão para sempre." },
  { reference: "Salmos 84:11", text: "Porquanto o Senhor Deus é sol e escudo; o Senhor dará graça e glória; não negará bem algum aos que andam na retidão." },
  { reference: "Salmos 86:7", text: "No dia da minha angústia clamo a ti, porque tu me respondes." },
  { reference: "Salmos 86:11", text: "Ensina-me, Senhor, o teu caminho, e andarei na tua verdade; dispõe o meu coração para temer o teu nome." },
  { reference: "Salmos 90:14", text: "Sacia-nos de manhã com a tua benignidade, para que nos regozijemos e nos alegremos todos os nossos dias." },
  { reference: "Salmos 91:1", text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Todo-Poderoso descansará." },
  { reference: "Salmos 91:2", text: "Direi do Senhor: Ele é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio." },
  { reference: "Salmos 91:4", text: "Ele te cobre com as suas penas, e debaixo das suas asas encontras refúgio; a sua verdade é escudo e broquel." },
  { reference: "Salmos 91:5", text: "Não temerás os terrores da noite, nem a seta que voe de dia." },
  { reference: "Salmos 91:10", text: "Nenhum mal te sucederá, nem praga alguma chegará à tua tenda." },
  { reference: "Salmos 91:11", text: "Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos." },
  { reference: "Salmos 91:14", text: "Pois que tanto me amou, eu o livrarei; pô-lo-ei num alto retiro, porque ele conhece o meu nome." },
  { reference: "Salmos 91:15", text: "Quando ele me invocar, eu lhe responderei; estarei com ele na angústia, livrá-lo-ei, e o honrarei." },
  { reference: "Salmos 91:16", text: "Com longura de dias fartá-lo-ei, e lhe mostrarei a minha salvação." },
  { reference: "Salmos 94:18", text: "Quando eu disse: O meu pé resvala; a tua benignidade, Senhor, me susteve." },
  { reference: "Salmos 94:19", text: "Quando os cuidados do meu coração se multiplicam, as tuas consolações recreiam a minha alma." },
  { reference: "Salmos 103:2", text: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum dos seus benefícios." },
  { reference: "Salmos 103:3", text: "É ele quem perdoa todas as tuas iniqüidades, quem sara todas as tuas enfermidades." },
  { reference: "Salmos 103:4", text: "Quem redime a tua vida da cova, quem te coroa de benignidade e de misericórdia." },
  { reference: "Salmos 107:19", text: "Então clamaram ao Senhor na sua tribulação, e ele os livrou das suas angústias." },
  { reference: "Salmos 107:20", text: "Enviou a sua palavra, e os sarou, e os livrou da destruição." },
  { reference: "Salmos 112:7", text: "Ele não teme más notícias; o seu coração está firme, confiando no Senhor." },
  { reference: "Salmos 116:1", text: "Amo ao Senhor, porque ele ouve a minha voz e a minha súplica." },
  { reference: "Salmos 116:2", text: "Porque inclina para mim o seu ouvido, invocá-lo-ei enquanto viver." },
  { reference: "Salmos 118:5", text: "Do meio da angústia invoquei o Senhor; o Senhor me ouviu, e me pôs em um lugar largo." },
  { reference: "Salmos 118:6", text: "O Senhor é por mim, não recearei; que me pode fazer o homem?" },
  { reference: "Salmos 118:17", text: "Não morrerei, mas viverei, e contarei as obras do Senhor." },
  { reference: "Salmos 119:28", text: "A minha alma se consome de tristeza; fortalece-me segundo a tua palavra." },
  { reference: "Salmos 119:50", text: "Isto é a minha consolação na minha angústia, que a tua promessa me vivifica." },
  { reference: "Salmos 119:76", text: "Sirva, pois, a tua benignidade para me consolar, segundo a palavra que deste ao teu servo." },
  { reference: "Salmos 119:105", text: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho." },
  { reference: "Salmos 119:114", text: "Tu és o meu refúgio e o meu escudo; espero na tua palavra." },
  { reference: "Salmos 121:1", text: "Elevo os meus olhos para os montes; de onde me vem o socorro?" },
  { reference: "Salmos 121:2", text: "O meu socorro vem do Senhor, que fez os céus e a terra." },
  { reference: "Salmos 121:3", text: "Não deixará vacilar o teu pé; aquele que te guarda não dormitará." },
  { reference: "Salmos 121:4", text: "Eis que não dormitará nem dormirá aquele que guarda a Israel." },
  { reference: "Salmos 121:5", text: "O Senhor é quem te guarda; o Senhor é a tua sombra à tua mão direita." },
  { reference: "Salmos 121:7", text: "O Senhor te guardará de todo o mal; ele guardará a tua vida." },
  { reference: "Salmos 121:8", text: "O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre." },
  { reference: "Salmos 125:1", text: "Aqueles que confiam no Senhor são como o monte Sião, que não pode ser abalado, mas permanece para sempre." },
  { reference: "Salmos 126:5", text: "Os que semeiam em lágrimas, com cânticos de júbilo segarão." },
  { reference: "Salmos 130:5", text: "Aguardo ao Senhor; a minha alma o aguarda, e espero na sua palavra." },
  { reference: "Salmos 138:3", text: "No dia em que eu clamei, atendeste-me; alentaste-me, fortalecendo a minha alma." },
  { reference: "Salmos 138:7", text: "Embora eu ande no meio da angústia, tu me revivificas; contra a ira dos meus inimigos estendes a tua mão, e a tua destra me salva." },
  { reference: "Salmos 139:1-3", text: "Senhor, tu me sondas, e me conheces. Tu conheces o meu sentar e o meu levantar; de longe entendes o meu pensamento. Esquadrinhas o meu andar, e o meu deitar, e conheces todos os meus caminhos." },
  { reference: "Salmos 139:7", text: "Para onde me irei do teu Espírito, ou para onde fugirei da tua presença?" },
  { reference: "Salmos 139:11-12", text: "Se eu disser: Ocultem-me as trevas; torne-se em noite a luz que me circunda; nem ainda as trevas são escuras para ti, mas a noite resplandece como o dia; as trevas e a luz são para ti a mesma coisa." },
  { reference: "Salmos 143:8", text: "Faze-me ouvir da tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti elevo a minha alma." },
  { reference: "Salmos 145:8", text: "Bondoso e compassivo é o Senhor, tardio em irar-se, e de grande benignidade." },
  { reference: "Salmos 145:9", text: "O Senhor é bom para todos, e as suas misericórdias estão sobre todas as suas obras." },
  { reference: "Salmos 145:14", text: "O Senhor sustém a todos os que estão a cair, e levanta a todos os que estão abatidos." },
  { reference: "Salmos 145:18", text: "Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade." },
  { reference: "Salmos 146:5", text: "Bem-aventurado aquele que tem o Deus de Jacó por seu auxílio, e cuja esperança está no Senhor seu Deus." },
  { reference: "Salmos 147:3", text: "Sara os quebrantados de coração, e cura-lhes as feridas." },
  { reference: "Salmos 147:11", text: "O Senhor se compraz nos que o temem, nos que esperam na sua benignidade." },
]);
